name: WebGL build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch: {}
jobs:
  build:
    name: WebGL build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-unity-webgl-gh-pages-deploy-sample-WebGL
          restore-keys: |
            Library-unity-webgl-gh-pages-deploy-sample-
            Library-

      - name: WebGL build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 2020.3.4f1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build/WebGL/WebGL

      - name: Upload the WebGL Build
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build